[home]
from              = Ralph Torres <mail@ralphptorr.es>
source            = imaps://ralphptorres@imap.mail.me.com
outgoing          = smtps+login://mail%40ralphptorr.es@smtp.mail.me.com
source-cred-cmd   = rbw get apple -f boron
outgoing-cred-cmd = rbw get apple -f boron
default           = INBOX
folders-sort      = INBOX
copy-to           = Sent Messages
cache-headers     = true

[work-ateneo]
from              = Ralph Torres <ralph.torres@student.ateneo.edu>
source            = imaps://ralph.torres%40student.ateneo.edu@imap.gmail.com
outgoing          = smtps://ralph.torres%40student.ateneo.edu@smtp.gmail.com
source-cred-cmd   = rbw get tok/google
outgoing-cred-cmd = rbw get tok/google
default           = INBOX
copy-to           = [Gmail]/Sent Mail
cache-headers     = true
