[home]
from              = Ralph Torres <mail@ralphptorr.es>
source            = imaps://ralphptorres@imap.mail.me.com
outgoing          = smtps+login://ralphptorres%40icloud.com@smtp.mail.me.com
source-cred-cmd   = rbw get apple -f boron
outgoing-cred-cmd = rbw get apple -f boron
default           = INBOX
folders-sort      = INBOX
copy-to           = Sent Messages
cache-headers     = true

[home-gmail]
from              = Ralph Torres <ralphotorres@gmail.com>
source            = imaps://ralphotorres%40gmail.com@imap.gmail.com
outgoing          = smtps://ralphotorres%40gmail.com@smtp.gmail.com
source-cred-cmd   = rbw get google -f boron
outgoing-cred-cmd = rbw get google -f boron
default           = INBOX
archive           = [Gmail]/All Mail
copy-to           = [Gmail]/Sent Mail
cache-headers     = true

[work-embiggen]
from              = Ralph Torres <ralphtorres@embiggengroup.com>
source            = imaps://ralphtorres%40embiggengroup.com@imap.gmail.com
outgoing          = smtps://ralphtorres%40embiggengroup.com@smtp.gmail.com
source-cred-cmd   = rbw get google-embiggen -f boron
outgoing-cred-cmd = rbw get google-embiggen -f boron
default           = INBOX
archive           = [Gmail]/All Mail
copy-to           = [Gmail]/Sent Mail
cache-headers     = true

[work-ateneo]
from              = Ralph Torres <rptorres@ateneo.edu>
source            = imaps://rptorres%40ateneo.edu@imap.gmail.com
outgoing          = smtps://rptorres%40ateneo.edu@smtp.gmail.com
source-cred-cmd   = rbw get google-ateneo -f boron
outgoing-cred-cmd = rbw get google-ateneo -f boron
default           = INBOX
archive           = [Gmail]/All Mail
copy-to           = [Gmail]/Sent Mail
cache-headers     = true

[work-s.ateneo]
from              = Ralph Torres <ralph.torres@student.ateneo.edu>
source            = imaps://ralph.torres%40student.ateneo.edu@imap.gmail.com
outgoing          = smtps://ralph.torres%40student.ateneo.edu@smtp.gmail.com
source-cred-cmd   = rbw get google-ateneo-student -f boron
outgoing-cred-cmd = rbw get google-ateneo-student -f boron
default           = INBOX
archive           = [Gmail]/All Mail
copy-to           = [Gmail]/Sent Mail
cache-headers     = true
