[home]
from              = Ralph Torres <mail@ralphptorr.es>
source            = imaps://mail%40ralphptorr.es@mail.mailo.com
outgoing          = smtps+login://mail%40ralphptorr.es@mail.mailo.com
source-cred-cmd   = rbw get tok/mailo
outgoing-cred-cmd = rbw get tok/mailo
default           = INBOX
copy-to           = sent
cache-headers     = true

[work-ateneo]
from              = Ralph Torres <ralph.torres@student.ateneo.edu>
source            = imaps://ralph.torres%40student.ateneo.edu@imap.gmail.com
outgoing          = smtps://ralph.torres%40student.ateneo.edu@smtp.gmail.com
source-cred-cmd   = rbw get tok/google
outgoing-cred-cmd = rbw get tok/google
default           = INBOX
copy-to           = [Gmail]/Sent Mail
cache-headers     = true
