[general]
default-save-path = ~/Downloads

[ui]
# index-columns        = flags:4,name<20%,subject,date>=
index-columns        = date<=, name<20, flags>=, subject<*, notmuch>=
column-notmuch       = {{- (map .Labels (exclude .Folder) (exclude "replied|passed|attachment|flagged|unread|draft") | join ",") -}}
sidebar-width        = 15
message-list-split   = horizontal 50
mouse-enabled        = true
dirlist-tree         = true
styleset-name        = monochrome
fuzzy-complete       = true
reverse-thread-order = true
sort-thread-siblings = true
threading-enabled    = true
thread-prefix-tip    = "─"

[statusline]
display-mode = icon

[viewer]

[compose]
# edit-headers          = true
focus-body            = true
address-book-cmd      = notmuch address "%s"
empty-subject-warning = true
no-attachment-warning = ^[^>]*attach(ed|ment)

[multipart-converters]
text/html = pandoc -f markdown -t html --standalone

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html = pandoc -f html -t plain | colorize
# text/html=! html
# text/html=! w3m -T text/html -I UTF-8
# text/*=bat -fP --file-name="$AERC_FILENAME"
# application/x-sh=bat -fP -l sh
# image/*=catimg -w $(tput cols) -
# subject,~Git(hub|lab)=lolcat -f
# from,thatguywhodoesnothardwraphismessages=wrap -w 100 | colorize
.headers=colorize

[openers]

[hooks]
mail-received = notify-send "[$AERC_ACCOUNT/$AERC_FOLDER] New mail from $AERC_FROM_NAME" "$AERC_SUBJECT"
# mail-deleted  = mbsync "$AERC_ACCOUNT:$AERC_FOLDER" &
# mail-added    = mbsync "$AERC_ACCOUNT:$AERC_FOLDER" &
# aerc-startup  = aerc :terminal calcurse && aerc :next-tab
# aerc-shutdown =
# tag-modified  =
# flag-changed  = mbsync "$AERC_ACCOUNT:$AERC_FOLDER" &
