inbox = tag:inbox and not tag:archived and not tag:deleted
todo  = tag:todo and not tag:archived and not tag:spam
all   = not tag:archived and not tag:deleted and not tag:spam
sent  = tag:sent
spam  = tag:spam
