# model: claude:claude-sonnet-4-5-20250929:thinking
# model: claude:claude-sonnet-4-5-20250929
# model: claude:claude-sonnet-4-20250514
# model: claude:claude-3-7-sonnet-20250219:thinking
model: claude:claude-3-7-sonnet-20250219
# model: claude:claude-3-5-haiku-20241022

# model: gemini:gemini-2.5-pro
# model: gemini:gemini-2.5-flash
# model: gemini:gemini-2.5-flash-lite

# model: mistral:mistral-medium-latest
# model: mistral:mistral-small-latest
# model: mistral:magistral-medium-latest
# model: mistral:magistral-small-latest
# model: mistral:codestral-latest

# model: openai:chatgpt-4o-latest
# model: openai:o3-mini-high
# model: openai:gpt-4o-mini

temperature: null
top_p: null
keybindings: vi
light_theme: true
repl_prelude: session:temp
save_session: true
wrap: auto

clients:
  - type: claude
    api_base: https://api.anthropic.com/v1
    api_key: ***
  - type: gemini
    api_base: https://generativelanguage.googleapis.com/v1beta
    api_key: ***
  - type: openai
    api_base: https://api.openai.com/v1
    api_key: ***
  - type: openai-compatible
    name: mistral
    api_base: https://api.mistral.ai/v1
    api_key: ***
    # api_base: https://codestral.mistral.ai/v1/fim/completions
    # api_key: ***
