#!/bin/sh

# map keys

for mode in normal locked
do
    riverctl map $mode None XF86MonBrightnessDown  spawn "adjuster backlight - 5"
    riverctl map $mode None XF86MonBrightnessUp    spawn "adjuster backlight + 5"
    riverctl map $mode Shift XF86MonBrightnessDown spawn "adjuster backlight = 2"
    riverctl map $mode Shift XF86MonBrightnessUp   spawn "wlr-randr --output eDP-1 --toggle"
    riverctl map $mode None XF86LaunchA            spawn "test"
    riverctl map $mode None XF86LaunchB            spawn "test"
    riverctl map $mode Shift XF86LaunchA           spawn "test"
    riverctl map $mode Shift XF86LaunchB           spawn "test"
    riverctl map $mode None XF86KbdBrightnessDown  spawn "adjuster keyboard - 7"
    riverctl map $mode None XF86KbdBrightnessUp    spawn "adjuster keyboard + 7"
    riverctl map $mode Shift XF86KbdBrightnessDown spawn "test"
    riverctl map $mode Shift XF86KbdBrightnessUp   spawn "test"
    riverctl map $mode None XF86AudioPrev          spawn "playerctl previous"
    riverctl map $mode None XF86AudioPlay          spawn "playerctl play-pause || ncmpcpp"
    riverctl map $mode None XF86AudioNext          spawn "playerctl next"
    riverctl map $mode Shift XF86AudioPrev         spawn "playerctl position 5-"
    riverctl map $mode Shift XF86AudioPlay         spawn "playerctl shuffle toggle"
    riverctl map $mode Shift XF86AudioNext         spawn "playerctl position 5+"
    riverctl map $mode None XF86AudioMute          spawn "adjuster vol_sink ="
    riverctl map $mode None XF86AudioLowerVolume   spawn "adjuster vol_sink - 5"
    riverctl map $mode None XF86AudioRaiseVolume   spawn "adjuster vol_sink + 5"
    riverctl map $mode Shift XF86AudioMute         spawn "adjuster vol_source ="
    riverctl map $mode Shift XF86AudioLowerVolume  spawn "adjuster vol_source - 5"
    riverctl map $mode Shift XF86AudioRaiseVolume  spawn "adjuster vol_source + 5"
done

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i                   set-focused-tags $tags
    riverctl map normal Super+Shift $i             set-view-tags $tags
    riverctl map normal Super+Alt $i               toggle-focused-tags $tags
    riverctl map normal Super+Alt+Shift $i         toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0             set-focused-tags $all_tags
riverctl map normal Super+Shift 0       set-view-tags $all_tags
riverctl declare-mode passthrough
riverctl map normal Super grave         enter-mode passthrough
riverctl map passthrough Super grave    enter-mode normal
# minus equal backspace

riverctl map normal Super Q             close
riverctl map normal Super+Alt+Control Q exit
riverctl map normal Super T             spawn "screenshotter"
riverctl map normal Super+Shift T       spawn "screenshotter menu"
riverctl map normal Super Y             spawn "fnottctl dismiss"
riverctl map normal Super+Shift Y       spawn "fnottctl dismiss all"
riverctl map normal Super U             spawn "eww close bar || eww open bar"
riverctl map normal Super+Shift U       spawn "eww close dash || eww open dash"
# E R I O P bracketleft bracketright backslash 

riverctl map normal Super F             toggle-fullscreen
riverctl map normal Super H             send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L             send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super J             focus-view next
riverctl map normal Super K             focus-view previous
riverctl map normal Super+Shift H       send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L       send-layout-cmd rivertile "main-count -1"
riverctl map normal Super+Shift J       swap next
riverctl map normal Super+Shift K       swap previous
riverctl map normal Super+Alt H         move left 100
riverctl map normal Super+Alt L         move right 100
riverctl map normal Super+Alt J         move down 100
riverctl map normal Super+Alt K         move up 100
riverctl map normal Super+Alt+Shift H   snap left
riverctl map normal Super+Alt+Shift L   snap right
riverctl map normal Super+Alt+Shift J   snap down
riverctl map normal Super+Alt+Shift K   snap up
riverctl map normal Super+Control H     resize horizontal -100
riverctl map normal Super+Control L     resize horizontal 100
riverctl map normal Super+Control J     focus-output next
riverctl map normal Super+Control K     focus-output previous
riverctl map normal Super+Control+Shift J send-to-output -current-tags next
riverctl map normal Super+Control+Shift K send-to-output -current-tags previous
riverctl map normal Super return        zoom
riverctl map normal Super+Shift return  toggle-float
# A S D G semicolon apostrophe 

riverctl map normal Super B             spawn "foot -e lf"
riverctl map normal Super+Shift B       spawn "firefox"
riverctl map normal Super N             spawn "obsidian"
riverctl map normal Super+Shift N       spawn "rnote"
riverctl map normal Super M             spawn "foot -e aerc"
riverctl map normal Super+Shift M       spawn "spotify"
riverctl map normal Super comma         spawn "fuzzel"
riverctl map normal Super+Shift comma   spawn "foot -a float -e fuzzy"
riverctl map normal Super period        spawn "menuemoji"
riverctl map normal Super+Shift period  spawn "menuemoji copy"
riverctl map normal Super slash         spawn "menupass"
riverctl map normal Super+Shift slash   spawn "menupass2"
# Z X C V 

riverctl map normal Super space         spawn "footclient || foot --server"
riverctl map normal Super+Shift space   spawn "foot"
riverctl map normal Super left          send-layout-cmd rivertile "main-location left"
riverctl map normal Super right         send-layout-cmd rivertile "main-location right"
riverctl map normal Super down          send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super up            send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Shift left    focus-output previous
riverctl map normal Super+Shift right   focus-output next
riverctl map normal Super+Shift down    send-to-output previous
riverctl map normal Super+Shift up      send-to-output next

riverctl map-pointer normal Super BTN_LEFT   move-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float
riverctl map-pointer normal Super BTN_RIGHT  resize-view
# riverctl map-switch normal lid close         spawn "waylock"
riverctl map-switch normal lid close         spawn "systemctl suspend"

# manage rules

riverctl rule-add -app-id "float" float
riverctl rule-add -app-id "*" ssd

# configure ui

riverctl attach-mode            top
riverctl background-color       0x0b0e0d # k tees
riverctl border-color-unfocused 0xfafef9 # w tix0
riverctl border-color-focused   0x007bc0 # b case0.d
riverctl border-color-urgent    0xf75f59 # r shot0
riverctl border-width           1

riverctl focus-follows-cursor   normal
riverctl hide-cursor timeout    0
riverctl set-cursor-warp        on-focus-change
riverctl xcursor-theme          BreezeX-Dark 45

riverctl set-repeat 50 300
riverctl input pointer-1452-* natural-scroll enabled
riverctl input pointer-1452-* tap enabled
if riverctl list-inputs | grep -qe keyboard-6700-*
then
	riverctl keyboard-layout -options \
		caps:swapescape,shift:both_capslock,altwin:swap_alt_win us
else
	riverctl keyboard-layout -options \
		caps:swapescape,shift:both_capslock,ctrl:swap_ralt_rctl us
fi

riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-location left -main-count 1 -main-ratio 0.5 &

# NOTE: color-scheme does not work with libadwaita for gtk4 apps, has to use
# libadwaita-without-adwaita then set gtk-theme instead
gsettings set org.gnome.desktop.interface color-scheme prefer-light
gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3
gsettings set org.gnome.desktop.interface cursor-theme BreezeX-Dark
gsettings set org.gnome.desktop.interface cursor-size 45
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river # for xdpw

# execute external utils

# swaybg -m fill -i "$(find $HOME/home/pic/imel-mono -type f | shuf -n1)" &
# swaybg -m fill -i "$(find $HOME/home/pic/interstellar -type f | shuf -n1)" &
# swaybg -m fill -i "$(find $HOME/home/pic/kirokaze-gifs -type f | shuf -n1)" &
swaybg -m fill -i "$(find $HOME/home/pic/libreshot-city -type f | shuf -n1)" &
# swaybg -m fill -i "$(find $HOME/home/pic/libreshot-street -type f | shuf -n1)" &
foot --server &
kanshi &
fnott &
swayidle &
yambar &
wayneko --layer top --survive-close &
mpd && mpd-mpris &

for drive in gdrive ncloud
do
	dir=$HOME/home/mnt/$drive
	mkdir -p $dir
	rclone mount $drive: $dir &
done

for drive in odrive
do
	dir=$HOME/home/mnt/$drive
	mkdir -p $dir
	rclone mount $drive: $dir --vfs-cache-mode writes &
done
