ol: &ol {overline: {size: 2, color: fafef9ff}}
ul: &ul {underline: {size: 2, color: fafef9ff}}
oul: &oul {stack: [*ol, *ul]}
rmp: &rmp # ⡀⣀⣄⣤⣦⣶⣷⣿ ⢀⣀⣠⣤⣴⣶⣾⣿
  - string: {text: "⡀"}
  - string: {text: "⣀"}
  - string: {text: "⣄"}
  - string: {text: "⣤"}
  - string: {text: "⣦"}
  - string: {text: "⣶"}
  - string: {text: "⣷"}
  - string: {text: "⣿"}
prg: &prg # ⣏⣿⡷⣉⣹ ⠯⠿⠗⠭⠽ ⠦⠶⠦⠤⠴
  start:     {string: {text: ""}}
  end:       {string: {text: "⣹"}}
  fill:      {string: {text: "⣿"}}
  empty:     {string: {text: "⣉"}}
  indicator: {string: {text: "⡷"}}
  font: monospace:style=extrabold:size=5
  length: 50

# TODO: fix font size, emoji color
bar:
  height: 30
  location: bottom
  background: 0b0e0dff # k tees
  spacing: 5
  margin: 10
  font: monospace:style=light:size=14
  foreground: fafef9ff # w tix0

  border:
    width: 10
    color: 0b0e0dff

  left:
    - river:
        anchors:
          - base: &rid
              margin: 5
              default: {empty: {}}
              conditions:
                id < 10: {string: {text: "{id}"}}
                id == 10: {string: {text: "*"}}
        title:
          - map:
              margin: 5
              conditions:
                mode == passthrough: {string: {text: "🔄"}}
                layout == "rivertile - top": {string: {text: "⬆️"}}
                layout == "rivertile - left": {string: {text: "⬅️"}}
                layout == "rivertile - right": {string: {text: "➡️"}}
                layout == "rivertile - bottom": {string: {text: "⬇️"}}
          - string: {text: "{title}", max: 30}
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            conditions:
              urgent && focused: {map: {<<: *rid, deco: *oul}}
              urgent: {map: {<<: *rid, deco: *ol}}
              focused: {map: {<<: *rid, deco: *ul}}
              occupied: {map: {<<: *rid}}
    - script:
        path: ~/.local/bin/yquery
        args: ["lyrics"]
        content:
          - string: {text: "🎼"}
          - string: {text: "{lyric}"}

  # TODO: add yquery (pacman, weather)
  center:
    - label:
        content: {empty: {}}
    - script:
        poll-interval: 1000
        path: ~/.local/bin/yquery
        args: ["music"]
        content:
          - map:
              default:
                string:
                  on-click: footclient -e ncspot
                  text: "🎵"
              conditions:
                set:
                  - map:
                      on-click: playerctl play-pause
                      default: {empty: {}}
                      conditions:
                        progset:
                          progress-bar: {<<: *prg, tag: progval}
                  - map:
                      on-click: playerctl play-pause
                      conditions:
                        status == Playing: {string: {text: "⏸️"}}
                        status == Paused:  {string: {text: "▶️"}}
                  - string:
                      on-click:
                        left: playerctl next
                        right: playerctl previous
                      text: "⏭️"
                  - string: {text: "{metadata}"}

  # TODO: add yquery (coffee), removables
  right:
    - pipewire:
        anchors:
          - base: &icon
              default: {string: {text: "{type} {form_factor} {icon}"}}
              conditions:
                type == sink:
                  map:
                    conditions:
                      form_factor == speaker:    {string: {text: "🔊"}}
                      form_factor == headphones: {string: {text: "🎧"}}
                      form_factor == headset:    {string: {text: "🎧"}}
                type == source:
                  map:
                    conditions:
                      form_factor == mic:        {string: {text: "🎤"}}
                      form_factor == headset:    {string: {text: "🎙"}}
        content:
          - map:
              left-margin: 10
              conditions:
                ~muted: {map: {<<: *icon}}
                muted:  {map: {<<: *icon, deco: *ul}}
          - ramp: {items: *rmp, tag: cubic_volume}
    - backlight:
        name: acpi_video0
        content:
          - string: {text: "🔆"}
          - ramp: {items: *rmp, tag: percent}
    - mem:
        content:
          - string: {text: "🗄"}
          - ramp: {items: *rmp, tag: percent_used}
    - cpu:
        content:
          - map:
              conditions:
                id < 0: {string: {text: "🧮"}}
          - ramp: {items: *rmp, tag: cpu}
    - network:
        poll-interval: 250
        spacing: 5
        anchors:
          - base: &speed
              map:
                conditions:
                  state != up: {string: {text: "*"}}
                  state == up:
                    - ramp: {items: *rmp, tag: dl-speed, max: 50000000} # 50 Mbps
                    - ramp: {items: *rmp, tag: ul-speed, max: 50000000}
        content:
          - map:
              conditions:
                name == wlan0 && ssid != "":
                  - string: {text: "🛜"}
                  - ramp: {items: *rmp, tag: quality}
                  - <<: *speed
                  - string: {text: "{ssid}", max: 3}
                name == enp0s20f0u1c4i2:
                  - string: {text: "📶"}
                  - <<: *speed
                name == wlan0:
                  - string: {text: "🛜"}
    - battery:
        name: BAT0
        poll-interval: 2000
        content:
          - map:
              conditions:
                state == discharging:  {string: {text: "🔋"}}
                state == charging:     {string: {text: "⚡"}}
                state == full:         {string: {text: "🔌"}}
                state == unknown:      {string: {text: "🔌*"}}
                state == not_charging: {string: {text: "🔌*"}}
          - ramp: {items: *rmp, tag: capacity, max: 70}
          - map:
              default: {string: {text: " {capacity}"}}
              conditions:
                state == discharging || state == charging:
                  - string: {text: " {capacity} {estimate}"}
    - label: {content: {string: {text: "|"}}}
    - clock:
        time-format: "%H%M"
        date-format: "%a %m%d"
        utc: true
        content: {string: {text: "{date} {time}"}}
    - label: {content: {string: {text: "|"}}}
    - label:
        content:
          string:
            on-click:
              left: quick wall
              right: sh -c "killall yambar && yambar"
              middle: pkill -USR1 swayidle
            text: "🦊🐧"
