ol: &ol {overline: {size: 2, color: fafef9ff}}
ul: &ul {underline: {size: 2, color: fafef9ff}}
oul: &oul {stack: [*ol, *ul]}
rmp: &rmp # ⡀⣀⣄⣤⣦⣶⣷⣿ ⢀⣀⣠⣤⣴⣶⣾⣿
  - string: {text: "⡀"}
  - string: {text: "⣀"}
  - string: {text: "⣄"}
  - string: {text: "⣤"}
  - string: {text: "⣦"}
  - string: {text: "⣶"}
  - string: {text: "⣷"}
  - string: {text: "⣿"}

# TODO: fix font size, emoji color
bar:
  height: 30
  location: bottom
  background: 0b0e0dff # k tees
  spacing: 5
  margin: 10
  font: monospace:style=light:size=14
  foreground: fafef9ff # w tix0

  border:
    width: 10
    color: 0b0e0dff

  # TODO: add river orientation
  left:
    - river:
        anchors:
          - base: &rid
              margin: 5
              default: {empty: {}}
              conditions:
                id < 10: {string: {text: "{id}"}}
                id == 10: {string: {text: "*"}}
        title: {string: {text: " {title}", max: 30}}
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
            conditions:
              urgent && focused: {map: {<<: *rid, deco: *oul}}
              urgent: {map: {<<: *rid, deco: *ol}}
              focused: {map: {<<: *rid, deco: *ul}}
              occupied: {map: {<<: *rid}}

  # TODO: add yquery (pacman, weather, media)
  center:
    - label:
        content: {empty: {}}

  # TODO: add yquery (coffee), backlight, mem, pipewire, removables
  right:
    - cpu:
        content:
          - map:
              conditions:
                id < 0: {string: {text: "🧮"}}
          - ramp: {items: *rmp, tag: cpu}
    - network:
        poll-interval: 250
        spacing: 5
        anchors:
          - base: &speed
              map:
                conditions:
                  state != up: {string: {text: "*"}}
                  state == up:
                    - ramp: {items: *rmp, tag: dl-speed, max: 50000000} # 50 Mbps
                    - ramp: {items: *rmp, tag: ul-speed, max: 50000000}
        content:
          - map:
              conditions:
                name == wlan0 && ssid != "":
                  - string: {text: "🛜"}
                  - ramp: {items: *rmp, tag: quality}
                  - <<: *speed
                  - string: {text: "{ssid}", max: 3}
                name == enp0s20f0u1c4i2:
                  - string: {text: "📶"}
                  - <<: *speed
                name == wlan0:
                  - string: {text: "🛜"}
    - battery:
        name: BAT0
        poll-interval: 2000
        content:
          - map:
              conditions:
                state == discharging:  {string: {text: "🔋"}}
                state == charging:     {string: {text: "⚡"}}
                state == full:         {string: {text: "🔌"}}
                state == unknown:      {string: {text: "🔌*"}}
                state == not_charging: {string: {text: "🔌*"}}
          - ramp: {items: *rmp, tag: capacity, max: 70}
          - map:
              default: {string: {text: " {capacity}"}}
              conditions:
                state == discharging || state == charging:
                  - string: {text: " {capacity} {estimate}"}
    - clock:
        time-format: "%H%M"
        date-format: "%a %m%d"
        utc: true
        content: {string: {text: "{date} {time}"}}
    - label: {content: {string: {text: "🦊🐧"}}}
