music_directory "~/home/aud"
playlist_directory "~/home/aud/playlist"
state_file "~/.local/share/mpd/mpdstate"
db_file "~/.local/share/mpd/mpd.db"

audio_output {
	type "pipewire"
	name "pipewire"
}

# audio_output {
# 	type "osx"
# 	name "osx"
# }

audio_output {
	type "fifo"
	name "visualizer"
	path "/tmp/mpd.fifo"
	format "44100:16:2"
}
