[main]
min-width=400
max-width=400
max-height=400
max-icon-size=400
# max-icon-size=150
anchor=bottom-right
selection-helper=fuzzel --dmenu
play-sound=pw-cat -p ${filename}

background=0b0e0dff # k tees
border-color=0b0e0dff
padding-vertical=10
padding-horizontal=10
title-font=monospace:weight=light:size=12
title-color=fafef9ff # w tix0
title-format=
summary-font=monospace:weight=light:size=12
summary-color=fafef9ff
body-font=monospace:weight=light:size=12
body-color=fafef9ff
progress-bar-color=fafef9ff
default-timeout=10
sound-file=/usr/share/sounds/freedesktop/stereo/message.oga

[low]
border-color=0b0e0dff

[normal]
border-color=fafef9ff

[critical]
border-color=00a4ffff # b case0
padding-vertical=40
padding-horizontal=40
default-timeout=0
