theme = "base16_default"

[editor]

line-number = "relative"
rulers = [80,100]

lsp.display-inlay-hints = true
indent-guides.render = true
soft-wrap.enable = true
smart-tab.supersede-menu = true

[keys.normal.' ']

'=' = ":reflow"
'.' = ":pipe-to tmux load-buffer - \\; paste-buffer -dpr \\; send-keys Enter"
',' = "@/^#<space>%%<ret>Ni#<esc>nF<ret>;vg.<esc>_<space>.un"
'>' = ":sh footclient tmux new -n repl '. ./../../.venv/bin/activate; ipython'"
