[language-server]

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]

[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"

[language-server.texlab.config.texlab]
build.forwardSearchAfter = true
build.onSave = true
chktex.onEdit = true
chktex.onOpenAndSave = true
forwardSearch.executable = "zathura"
forwardSearch.args = ["--synctex-forward", "%l:1:%f", "%p"]
bibtexFormatter = "texlab"
latexFormatter = "tex-fmt" # or texlab

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "onType"
formatterProseWrap = true
lint.enabled = true
lint.when = "onSave"

[language-server.typos-lsp]
command = "typos-lsp"

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "latex"
language-servers = ["texlab", "typos-lsp"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'$' = '$'

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = ["markdown-oxide", "typos-lsp"]
comment-tokens = ["-", "*", "- [ ]", ">"]

[[language]]
name = "python"
language-servers = ["ruff", "pylyzer"]

[[language]]
name = "toml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"
language-servers = ["tinymist"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }
