[language-server]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
config.basedpyright.analysis.typeCheckingMode = "basic"

[language-server.gpt]
command = "helix-gpt"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.rust-analyzer.config]
cargo.features = "all"
check.command = "clippy"

[language-server.texlab.config.texlab]
build.forwardSearchAfter = true
build.onSave = true
chktex.onEdit = true
chktex.onOpenAndSave = true
forwardSearch.executable = "zathura"
forwardSearch.args = ["--synctex-forward", "%l:1:%f", "%p"]
bibtexFormatter = "texlab"
latexFormatter = "tex-fmt" # or texlab

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "onType"
formatterProseWrap = true
lint.enabled = true
lint.when = "onSave"

[language-server.typos-lsp]
command = "typos-lsp"
config.diagnosticSeverity = "Hint"

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "latex"
language-servers = ["texlab", "typos-lsp"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
'$' = '$'

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = ["gpt", "markdown-oxide", "typos-lsp"]
comment-tokens = ["-", "*", "- [ ]", ">"]

[[language]]
name = "python"
auto-format = true
language-servers = ["basedpyright", "gpt", "ruff", "ty"]

[[language]]
name = "toml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle", args = ["--wrap-text"] }
language-servers = ["gpt", "tinymist"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }
